//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportWpfApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.OrderProduct = new HashSet<OrderProduct>();
        }
    
        public string Id { get; set; }
        public string Name { get; set; }
        public string MeasurementUnit { get; set; }
        public Nullable<int> Cost { get; set; }
        public Nullable<int> MaxDiscountAmount { get; set; }
        public Nullable<int> ActualDiscountAmount { get; set; }
        public Nullable<int> StockQuanitity { get; set; }
        public Nullable<int> ManufacturerId { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public Nullable<int> ProductCategoryId { get; set; }
        public string Description { get; set; }
        public byte[] Image { get; set; }
    
        public virtual Manufacturer Manufacturer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderProduct> OrderProduct { get; set; }
        public virtual ProductCategory ProductCategory { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
